### ISSUE TITLE
OnlineSimDriver is not a constructor

### ISSUE THREAD

**Issue by simeon105** [s00d/onlinesim-js-api#2]
When I write for example const driver = new OnlineSimDriver(apikey); it gives me error like "OnlineSimDriver is not a constructor". I am using nodejs with typescript. Can someone please tell me hot to fix it?

This is  my main code in index.ts:
```js
import OnlineSimDriver from "onlinesim-js-api";

const apikey = 'key';
const driver = new OnlineSimDriver(apikey, 'en', null);
driver.user().balance().then((result: any) => {
    console.log(result);
})
```

This is my tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "sourceMap": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "removeComments": true,
  },
  "exclude": [
    "node_modules"
  ]
}
```

This is the error:
![image](https://user-images.githubusercontent.com/48362439/146636405-af317c4d-3b46-4aa9-9d9f-49612a346aa7.png)
TypeError: OnlineSimDriver is not a constructor

**Comment by lomaka1313** [comment]
Correct import for this library in TS looks like
`import { default as OnlineSimDriver } from 'onlinesim-js-api';`

**Comment by d2m22** [comment]
> Correct import for this library in TS looks like `import { default as OnlineSimDriver } from 'onlinesim-js-api';`
still an error:
import { default as OnlineSimDriver } from 'onlinesim-js-api';
^^^^^^
SyntaxError: Cannot use import statement outside a module

**Comment by lomaka1313** [comment]
> 

My comment can implement only for TS, are u sure that u use TS?

**Comment by d2m22** [comment]
Thanks. Didn't use TS. But, the problem still as described in the first post.

```
import OnlineSimDriver from "onlinesim-js-api"
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

or

```
const OnlineSimDriver = require("onlinesim-js-api");
const driver = new OnlineSimDriver(apikey);
               ^
TypeError: OnlineSimDriver is not a constructor
```

**Comment by s00d** [comment]
try import * as OnlineSimDriver from "onlinesim-js-api"

**Comment by d2m22** [comment]
Still an error:
```
import * as OnlineSimDriver from "onlinesim-js-api"
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

**Comment by s00d** [comment]
you have problems with project settings, try adding
```
{
  // ...
  "type": "module",
  // ...
}
```
to **package.json** file.

**Comment by d2m22** [comment]
After adding **"type": "module"** to **package.json** file, unfortunately, it still an error:
```
import OnlineSimDriver from "onlinesim-js-api";
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

**Comment by s00d** [comment]
I didn't notice that you are using ts

delete from package.json `"type": "module"`

change to tsconfig  `"module": "CommonJS",`

[example.zip](https://github.com/s00d/onlinesim-js-api/files/9175666/example.zip)

**Comment by d2m22** [comment]
May be the package files after a clean install on Windows help find the problem [onlinesim-js-api.zip](https://github.com/s00d/onlinesim-js-api/files/9176063/onlinesim-js-api.zip)

Tried it in a virtual machine with a fresh installed Ubuntu 20.04, the same error
```
const driver = new OnlineSimDriver(apikey);
               ^
TypeError: OnlineSimDriver is not a constructor
```

**Comment by s00d** [comment]
I posted a working example above. study it
launch via ts-node
```
ts-node index.ts
```
or node
```
tsc && node index.js
```

**Comment by RadonCoding** [comment]
same problem

**Comment by s00d** [comment]
try latest version
